### ISSUE TITLE
Add the donation link

### ISSUE THREAD

**Issue by manassolanki** [India-Fights-Pandemic/web-app#26]
**Donate feature request:**
A website visitor (International / Resident Indian) should be able to contribute towards Covid relief activities through one of the links provided on our site.

**Where** - Next to the Volunteer link, let us place a button for DONATE. Clicking on Donation opens Nodal window where we provide 3 Donation Links
- Donate via Goonj
- Donate via PM CARES
- Donate via Zomato Feed India campaign

Some more link: https://indiacovidresources.wordpress.com/blog/

**Links to be placed:** 

Goonj:
Indian Donors
Goonj :
Button Text: Donate
Button Link: https://goonj.org/donate/

International Donors: 
Link https://goonj.org/donate-foreign/
PM CARES: Button text: “Donate” 
Button Link: https://www.pmcares.gov.in/en/

Zomato Campaign: Button: “Donate”
Button link: https://www.feedingindia.org/donate/help-save-my-india

**Track:**
Number of people clicking on Donate link
No. Of folks clicking on Goonj/ PM Cares/Zomato links

**Tasks**
- [ ] Add the button for donation
- [ ] Add the tracker for keeping a track of donation

**Comment by manassolanki** [comment]
Hey @sanjredfield  can you pick this up (in case got some free time)?

**Comment by sanjredfield** [comment]
Sure, I can pick this up.

**Comment by suranah** [comment]
Thank you, @sanjredfield

**Comment by suranah** [comment]
Any update on this, @sanjredfield? This was a little urgent given the situation.

**Comment by sanjredfield** [comment]
Hi - it is done except for the tracking stuff. I message @manassolanki on slack to ask how we want to do the tracking, but haven't heard back yet.

**Comment by suranah** [comment]
@sanjredfield, Manas is down with fever & body pain. 

I think we can do without tracking for now. I will add the tracking later if @manassolanki takes longer to recover. 

Thank you!

**Comment by sanjredfield** [comment]
#32
