### ISSUE TITLE
Transition to Netlify

### ISSUE THREAD

**Issue by suranah** [India-Fights-Pandemic/web-app#31]
Need to transition our code & deployment from firebase to Vercel. This will include transferring our DNS & SSL from firebase and may lead to some site downtime.

**Comment by gaurav-** [comment]
Chose Netlify eventually as Vercel free plan allowed deployments only from personal Github repo and not from Github org repo.
Netlify domain: https://india-fights-pandemic.netlify.app/
DNS migration also done
